[package]
name = "rustlogcollector"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
axum = "0.8.7"
lz4_flex = "0.11"
serde = { version = "1.0", features = ["derive"] }
